language: ruby
rvm:
 - 2.4.1
sudo: required
services:
  - docker
script:
  - bundle exec rake test
after_success:
  - docker login -u $DOCKER_USER --password-stdin $DOCKER_PASSWORD
  - bundle exec rake push
addons:
  apt:
    packages:
      - docker-ce