language: ruby
rvm:
 - 2.6
sudo: required
services:
  - docker
script:
  - bundle install
  - bundle exec rake test
after_success:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
  - bundle exec rake push
addons:
  apt:
    packages:
      - docker-ce